apiVersion: my.domain/v1
kind: SecretManager
metadata:
  labels:
    app.kubernetes.io/name: secret-manager
    app.kubernetes.io/managed-by: kustomize
  name: secretmanager-sample
spec:
  name: test-secret
  sourceSecretName: dev/test
